#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: DeploymentTrainSchedule
    labels: 
        app: trainApp
        name: trainApp
spec:
    replicas: 1
    matchLabels:
        name: trainApp
        app: trainApp
    template:
        metadata:
        
            labels:
                name: trainApp
                app: trainApp
        spec:
            containers:
            - name: trainApp
              image: trainAppImage
              ports:
                - containerPort: 8080
              resources:
                  requests:
                    cpu: 200m
            